[build]
target = "target.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
panic-abort-tests = true
